thd_trip_point: fix 32-bit build error with musl v1.2.0
Error log:
 ../git/src/thd_trip_point.cpp: In member function 'bool cthd_trip_point::thd_trip_point_check(int, unsigned int, int, bool*)':
| ../git/src/thd_trip_point.cpp:250:19: error: format '%ld' expects argument of type 'long int', but argument 6 has type 'time_t' {aka 'long long int'} [-Werror=format=]
|   250 |      thd_log_info("Too early to act zone:%d index %d tm %ld\n",

musl 1.2.0 have new feature:
time_t is now 64-bit on all archs (not just 64-bit archs)

Commit id:
https://git.musl-libc.org/cgit/musl/commit/?id=38143339646a4ccce8afe298c34467767c899f51

Release note link for musl 1.2.0:
https://git.musl-libc.org/cgit/musl/diff/

use %jd and typecast with intmax_t which is maximum width integer type

Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>